### ISSUE TITLE
Enabling ACL 

### ISSUE THREAD

**Issue by SashaDgraph** [dgraph-io/dgraph-docs#305]
Enabling ACL requires a secret key generation, but there is no command given with which they can generate said file. Also, in the example given below the directions, they used the following command:
echo '12345678901234567890123456789012' > hmac_secret_file 
to generate the secret file. This is not randomly generated and is therefore not the best to use as an example.

Fixes: https://github.com/dgraph-io/dgraph-docs/issues/305

**Comment by MichelDiz** [comment]
Can you point out where did see this?

**Comment by SashaDgraph** [comment]
Enterprise Features > ACL > Enable enterprise ACL feature > Step 1 (where the command is missing)
Enterprise Features > ACL > Example using Dgraph CLI > this is where they use the echo command

**Comment by Rajakavitha1** [comment]
Closing this issue for now because the PR with the Fix has been merged. Please feel free to reopen if any other updates need to be made.

**Comment by SashaDgraph** [comment]
I can see on the documentation that the command for key creation is still not randomly generated. We are still using the echo <key>  > hmac_secret_file command. This command will always store the key value mentioned in the command in the hmac_secret_file. Shouldn't it be more like the key generation command for encryption where a random key is generated and then stored in the file? (Link for encryption page - https://dgraph.io/docs/enterprise-features/encryption-at-rest/) (Link for ACL page - https://dgraph.io/docs/enterprise-features/access-control-lists/)

**Comment by skrdgraph** [comment]
@MichelDiz ^ this what i had discussed with you, it's okay - we can open another PR for this. im reopening this issue

**Comment by Rajakavitha1** [comment]
@SashaDgraph  could you please review the changes made in the new PR 350?
